In [1]:
import torch

In [2]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

**Numbers in Python are objects**. Whereas a floating-point number might require
only, for instance, 32 bits to be represented on a computer, Python will convert
it into a full-fledged Python object with reference counting, and so on. This
operation, called boxing, is not a problem if we need to store a small number of
numbers, but allocating millions gets very inefficient.

 **Lists in Python are meant for sequential collections of objects.** There are no operations
defined for, say, efficiently taking the dot product of two vectors, or summing vectors together. Also, Python lists have no way of optimizing the layout of their contents in memory, as they are indexable collections of pointers to Python objects.

In [3]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [4]:
double_points.dtype

torch.float64

In [5]:
short_points.dtype

torch.int16

In [6]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [7]:
print(double_points.dtype)
print(short_points.dtype)

torch.float64
torch.int16


**some common operations on tensors**

In [8]:
a = torch.rand(3,2)
print(a)
a_t = torch.transpose(a, 0, 1)
a.shape, a_t.shape
print("========================")
print(a_t)

tensor([[0.3525, 0.1306],
        [0.4038, 0.3475],
        [0.7476, 0.9429]])
tensor([[0.3525, 0.4038, 0.7476],
        [0.1306, 0.3475, 0.9429]])


# Indexing into storage

In [9]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

<ipython-input-9-8575ff47c9e0>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [10]:
points.storage()[1]

1.0

We can’t index a storage of a 2D tensor using two indices. The layout of a storage is
always one-dimensional, regardless of the dimensionality of any and all tensors that
might refer to it

In [11]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
#indexing of tensor
points_storage[3] = 2.0
points

tensor([[4., 1.],
        [5., 2.],
        [2., 1.]])

In [12]:
some_t = torch.rand(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [13]:
some_t

tensor([[[0.8472, 0.9744, 0.9043, 0.6092, 0.5228],
         [0.0919, 0.4115, 0.0607, 0.6791, 0.8086],
         [0.1359, 0.3917, 0.2855, 0.7027, 0.1012],
         [0.5674, 0.5909, 0.9469, 0.8096, 0.4308]],

        [[0.0575, 0.9304, 0.2338, 0.2793, 0.5733],
         [0.5752, 0.9927, 0.6259, 0.2302, 0.3363],
         [0.9087, 0.6128, 0.8231, 0.8013, 0.7394],
         [0.2587, 0.0732, 0.1174, 0.9612, 0.9249]],

        [[0.8578, 0.3961, 0.2368, 0.0082, 0.0305],
         [0.3299, 0.2919, 0.5973, 0.0298, 0.0210],
         [0.4624, 0.3217, 0.7063, 0.8314, 0.5482],
         [0.0920, 0.6123, 0.6646, 0.9039, 0.5072]]])

In [14]:
transpose_t

tensor([[[0.8472, 0.0575, 0.8578],
         [0.0919, 0.5752, 0.3299],
         [0.1359, 0.9087, 0.4624],
         [0.5674, 0.2587, 0.0920]],

        [[0.9744, 0.9304, 0.3961],
         [0.4115, 0.9927, 0.2919],
         [0.3917, 0.6128, 0.3217],
         [0.5909, 0.0732, 0.6123]],

        [[0.9043, 0.2338, 0.2368],
         [0.0607, 0.6259, 0.5973],
         [0.2855, 0.8231, 0.7063],
         [0.9469, 0.1174, 0.6646]],

        [[0.6092, 0.2793, 0.0082],
         [0.6791, 0.2302, 0.0298],
         [0.7027, 0.8013, 0.8314],
         [0.8096, 0.9612, 0.9039]],

        [[0.5228, 0.5733, 0.0305],
         [0.8086, 0.3363, 0.0210],
         [0.1012, 0.7394, 0.5482],
         [0.4308, 0.9249, 0.5072]]])

In [15]:
some_t.stride()

(20, 5, 1)

In [16]:
transpose_t.stride()

(1, 5, 20)

In [17]:
some_t.is_contiguous()

True

In [18]:
transpose_t.is_contiguous()

False

In [19]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')


In [20]:
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [21]:
torch.save(points, 'points.t')

In [22]:
points=torch.load('points.t')

In [23]:
points

tensor([[4., 1.],
        [5., 2.],
        [2., 1.]])

**Tensor Views**
PyTorch allows a tensor to be a View of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting View avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.

In [24]:
t = torch.rand(4, 4)
b = t.view(2, 8)
t.storage().data_ptr() == b.storage().data_ptr()  # `t` and `b` share the same underlying data.
b[0][0] = 3.14
t[0][0]

tensor(3.1400)

In [26]:
base = torch.tensor([[0, 1],[2, 3]])
base.is_contiguous()

True

In [27]:

t = base.transpose(0, 1)  # `t` is a view of `base`. No data movement happened here.
t.is_contiguous()

False

In [28]:

c = t.contiguous()